
# Name your project! Project names should contain only lowercase characters
# and underscores. 
name: 'mophones_credit_analytics'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'mophones_credit_analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  mophones_credit_analytics:
    # This applies to all models in your project
    +materialized: view
